
import React from 'react';
import { HiveEntry, AnalysisResult } from '../types';

interface DoctorReportProps {
  entries: HiveEntry[];
  analysis: AnalysisResult | null;
}

const DoctorReport: React.FC<DoctorReportProps> = ({ entries, analysis }) => {
  const avgSeverity = entries.length > 0 
    ? (entries.reduce((acc, curr) => acc + curr.severity, 0) / entries.length).toFixed(1) 
    : '0';

  return (
    <div id="printable-report" className="hidden print:block p-12 bg-white text-slate-900">
      <div className="border-b-4 border-slate-900 pb-8 mb-10 flex justify-between items-start">
        <div className="space-y-2">
          <div className="text-[10px] font-black text-indigo-600 uppercase tracking-widest mb-1">Clinic Facility Branding</div>
          <div className="text-2xl font-black italic text-slate-300 border-2 border-dashed border-slate-200 p-4 inline-block mb-4">
            [Clinic Logo Here]
          </div>
          <h1 className="text-4xl font-black uppercase tracking-tighter">Clinical Data Summary</h1>
          <p className="text-slate-500 font-bold">Patient Protocol Report • Generated {new Date().toLocaleDateString()}</p>
        </div>
        <div className="text-right">
          <div className="bg-slate-900 text-white px-3 py-1 text-[10px] font-black uppercase tracking-widest inline-block mb-2 rounded">
            Restricted Medical Data
          </div>
          <p className="text-sm font-bold text-slate-600">Total Clinical Observations: {entries.length}</p>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-8 mb-12">
        <div className="bg-slate-50 p-6 border-2 border-slate-200 rounded-2xl">
          <p className="text-xs font-black text-slate-500 uppercase tracking-widest mb-2">Mean Severity Index</p>
          <p className="text-4xl font-black">{avgSeverity} <span className="text-sm text-slate-400">/ 10</span></p>
        </div>
        {analysis?.environmentInsights && (
          <div className="bg-indigo-50 p-6 border-2 border-indigo-200 rounded-2xl col-span-2">
            <p className="text-xs font-black text-indigo-700 uppercase tracking-widest mb-2">Environmental Correlation Telemetry</p>
            <p className="text-base font-bold text-indigo-900 leading-tight">"{analysis.environmentInsights}"</p>
          </div>
        )}
      </div>

      <div>
        <h2 className="text-xl font-black uppercase tracking-tight mb-6 border-b-2 border-slate-100 pb-3">Historical Observation Log</h2>
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-slate-100 text-[10px] font-black uppercase tracking-widest">
              <th className="p-3 border border-slate-200">Timestamp</th>
              <th className="p-3 border border-slate-200 w-16 text-center">Sev.</th>
              <th className="p-3 border border-slate-200">Environmental Data</th>
              <th className="p-3 border border-slate-200">Reported Triggers & Clinical Notes</th>
            </tr>
          </thead>
          <tbody>
            {entries.map(entry => (
              <tr key={entry.id} className="text-[11px] break-inside-avoid">
                <td className="p-3 border border-slate-200 font-bold">
                  {new Date(entry.timestamp).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}
                </td>
                <td className="p-3 border border-slate-200 font-black text-center text-sm">{entry.severity}</td>
                <td className="p-3 border border-slate-200 italic font-medium">
                  {entry.weather ? `${entry.weather.temp}°C, ${entry.weather.humidity}% Rel. Humidity (Pollen: ${entry.weather.pollenLevel || 'Not Logged'})` : 'No Telemetry'}
                </td>
                <td className="p-3 border border-slate-200">
                  <div className="font-bold mb-1">{entry.triggers || 'No triggers identified'}</div>
                  {entry.notes && <p className="text-slate-500 font-medium leading-relaxed">{entry.notes}</p>}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-16 pt-10 border-t-2 border-slate-100 text-center text-[10px] text-slate-400 font-bold uppercase tracking-[0.2em] space-y-2">
        <p>This document is generated by Clinical Hive Tracker Pro for medical monitoring purposes only.</p>
        <p>Facility: [Clinic Name Placeholder] • White-Label Clinical Asset</p>
      </div>
    </div>
  );
};

export default DoctorReport;
